version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
        - ~/volumes/jhd/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=jhd
      - MYSQL_ROOT_PASSWORD=Jhs[123
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080